version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    environment:
      POSTGRES_DB: healthcare_dev
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: local_dev_only
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d healthcare_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 